
environment:
  matrix:

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     configuration: Debug
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     configuration: Release
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     configuration: Retail
     platform: x64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
     buildcfg: debug64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
     buildcfg: release64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
     buildcfg: retail64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: debug64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: release64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: retail64

shallow_clone: true

install:
- git submodule init
- git submodule update

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
      - QTDIR: C:\Qt\6.4.2\msvc2019_64
    
    init:
    - set QTDIR_VS2019_x64=C:\Qt\6.4.2\msvc2019_64
    - set QTDIR_VS2019_x86=C:\Qt\6.4.2\msvc2019 
    - set PATH=C:\projects\rqt\luaforwindows\files;%QTDIR_VS2019_x64%\bin;%PATH%
    - echo %PATH%
    - echo %QTDIR_VS2019_x64%
    - dir %QTDIR_VS2019_x64%\bin
    - git clone --depth 1 https://github.com/milostosic/rqt     rqt
    - git clone --depth 1 https://github.com/milostosic/build   build
    - git clone --depth 1 https://github.com/milostosic/rbase   rbase
    - git clone --depth 1 https://github.com/milostosic/rdebug  rdebug
    - git clone --depth 1 https://github.com/milostosic/DIA     DIA
    - git clone --depth 1 https://github.com/milostosic/luaforwindows luaforwindows

    install:
      - build\tools\bin\windows\genie.exe --file=rqt\genie\genie.lua vs2019

    build: ../.build/windows/vs2019/rqt/projects/rqt.sln

# ======================================
# Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - sudo apt-get update
      - sudo apt-get install -y lua5.3 lua-filesystem build-essential libgl1-mesa-dev
      - export QTDIR="$HOME/Qt/6.4/gcc_64"
      - export PATH="$HOME/Qt/6.4/gcc_64/bin:$HOME/Qt/6.4/gcc_64/libexec:/home/appveyor/Qt/6.4/gcc_64/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.4/gcc_64/lib/pkgconfig"
      - export QTDIR_GMAKE_x64="$HOME/Qt/6.4/gcc_64"
      - export QTDIR_GMAKE_x86="$HOME/Qt/6.4/gcc_64" 
      - git clone --depth 1 https://github.com/milostosic/rqt     rqt
      - git clone --depth 1 https://github.com/milostosic/build   build
      - git clone --depth 1 https://github.com/milostosic/rbase   rbase
      - git clone --depth 1 https://github.com/milostosic/rdebug  rdebug
      - git clone --depth 1 https://github.com/bkaradzic/GENie    GENie		# build GENie from source: `GLIBC_2.29' not found
      - cd GENie && make && cd ..

    install:
      - ./GENie/bin/linux/genie --file=rqt/genie/genie.lua --gcc=linux-gcc-9 gmake
  
    build_script:
      - cd ./.build/linux/gcc-9/rqt/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - if [ ! -d ../vcpkg ]; then git clone https://github.com/microsoft/vcpkg.git ../vcpkg ; fi
      - "(cd ../vcpkg && git pull && ./bootstrap-vcpkg.sh)"
      - export VCPKG_DIR=`dirname $(pwd)/../vcpkg/vcpkg`
      - export QTDIR="$HOME/Qt/6.4/macos"
      - export PATH="$HOME/Qt/6.4/macos/bin:$HOME/Qt/6.4/macos/share/qt/libexec:/Users/appveyor/Qt/6.4/macos/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.4/macos/lib/pkgconfig"
      - export QTDIR_GMAKE_x64="$HOME/Qt/6.4/macos"
      - export QTDIR_GMAKE_x86="$HOME/Qt/6.4/macos" 
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - brew update
      - brew install lua luarocks qt6
      - sudo luarocks install luafilesystem	--check-lua-versions
      - git clone --depth 1 https://github.com/milostosic/rqt     rqt
      - git clone --depth 1 https://github.com/milostosic/rdebug  rdebug
      - git clone --depth 1 https://github.com/milostosic/build   build
      - git clone --depth 1 https://github.com/milostosic/rbase   rbase
    
    install:
      - ./build/tools/bin/darwin/genie --file=rqt/genie/genie.lua --gcc=osx gmake
    
    build_script:
      - cd ./.build/osx/clang/rqt/projects/
      - make config=${buildcfg}
